"""Post-freeze calibration-only teacher coverage audit for R7 shortlist R2.

The R2 shortlist generator is teacher-blind.  This comparator verifies every
generated byte before it opens calibration teacher labels, and never sends
those labels to formal AI inputs.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.v2_core_calibration_reference_alignment_v1 import load_reference_cases
from scripts.v2_core_legacy_role_shortlist_r7 import (
    ARTIFACT_DIR,
    canonical_bytes,
    load_json,
    sha256_path,
    write_new_or_identical,
)
from scripts.v2_core_legacy_role_shortlist_r7_v2 import OUTPUT_MANIFEST
from scripts.v2_core_legacy_role_shortlist_coverage_r7 import ROLE_BY_SCENARIO, markdown


REPORT_VERSION = "v2-core-legacy-role-shortlist-coverage-r7-r2"
FROZEN_GENERATOR_SHA256 = "e826e220efe721823804733f7f98996b0dc8fe9bf190e6abf74ceec7a42c347b"


def build_report(artifact_dir: Path, *, generator_path: Path | None = None) -> dict[str, Any]:
    generator_path = generator_path or ROOT / "scripts" / "v2_core_legacy_role_shortlist_r7_v2.py"
    if sha256_path(generator_path) != FROZEN_GENERATOR_SHA256:
        raise ValueError("R7 R2 shortlist generator changed after freeze; refuse teacher audit")
    manifest_path = artifact_dir / OUTPUT_MANIFEST
    manifest = load_json(manifest_path)
    if manifest["teacher_answers_read"] or manifest["locked_set_read"] or manifest["future_performance_used"]:
        raise ValueError("shortlist manifest violates blindness contract")

    shortlists: dict[str, dict[str, Any]] = {}
    for row in manifest["rows"]:
        path = artifact_dir / manifest["shortlist_directory"] / row["shortlist_file"]
        if sha256_path(path) != row["shortlist_sha256"]:
            raise ValueError(f"shortlist hash mismatch: {row['review_id']}")
        payload = load_json(path)
        if payload["review_id"] != row["review_id"] or payload["source_packet_sha256"] != row["source_packet_sha256"]:
            raise ValueError(f"shortlist source binding mismatch: {row['review_id']}")
        if payload["contract"]["teacher_answers_read"] or payload["contract"]["course_role_selected_by_program"]:
            raise ValueError(f"shortlist contract violation: {row['review_id']}")
        shortlists[row["review_id"]] = payload

    references = load_reference_cases(artifact_dir)
    cases: list[dict[str, Any]] = []
    for review_id in sorted(shortlists):
        reference = references.get(review_id)
        if not reference or not reference.positive or not reference.structured_legacy_reference:
            raise ValueError(f"missing structured calibration teacher: {review_id}")
        anchor = reference.legacy_trigger["macro_anchor"]
        scenario = reference.legacy_trigger["scenario"]
        role = ROLE_BY_SCENARIO[scenario]
        role_data = shortlists[review_id]["roles"][role]
        matches = [
            row for row in role_data["candidate_rows"]
            if row["direction"] == anchor["direction"]
            and row["start_date"] == anchor["start"]
            and row["confirmed_end_date"] == anchor["end"]
        ]
        cases.append({
            "review_id": review_id,
            "teacher_scenario": scenario,
            "target_role": role,
            "teacher_anchor_direction": anchor["direction"],
            "teacher_anchor_start": anchor["start"],
            "teacher_anchor_end": anchor["end"],
            "role_shortlist_count": role_data["shortlist_count"],
            "exact_teacher_anchor_retained": bool(matches),
            "matching_candidate_ids": [row["candidate_id"] for row in matches],
        })
    covered = sum(int(case["exact_teacher_anchor_retained"]) for case in cases)
    count = len(cases)
    return {
        "report_version": REPORT_VERSION,
        "status": "ROLE_SHORTLIST_COVERAGE_READY" if covered == count else "ROLE_SHORTLIST_COVERAGE_REVISION_REQUIRED",
        "scope": "CALIBRATION_ONLY_POST_FREEZE_TEACHER_COVERAGE_AUDIT",
        "generator_sha256": FROZEN_GENERATOR_SHA256,
        "shortlist_manifest_sha256": sha256_path(manifest_path),
        "case_count": count,
        "exact_role_working_anchor_covered_count": covered,
        "coverage_percent": round(100.0 * covered / count, 2) if count else None,
        "formal_ai_calls": 0,
        "teacher_values_sent_to_ai": False,
        "locked_set_opened": False,
        "future_performance_used": False,
        "cases": cases,
        "interpretation": (
            "Coverage proves candidate representability only. It does not prove AI role selection, "
            "scenario alignment, trade-path reproduction, consistency or positive expectancy."
        ),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--artifact-dir", type=Path, default=ARTIFACT_DIR)
    args = parser.parse_args()
    report = build_report(args.artifact_dir)
    json_path = args.artifact_dir / "legacy_role_shortlist_coverage_candidate_r7_v2.json"
    md_path = args.artifact_dir / "legacy_role_shortlist_coverage_candidate_r7_v2.md"
    write_new_or_identical(json_path, canonical_bytes(report))
    write_new_or_identical(md_path, (markdown(report) + "\n").encode("utf-8"))
    print(json.dumps({"status": report["status"], "coverage_percent": report["coverage_percent"]}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
